In [1]:
# Q.01] Create a numpy array 'arr' of integers from 0 to 5 and print its datatypes ?

import numpy as np

arr = np.array([0,1,2,3,4,5])

print(arr.dtype)

int64


In [2]:
# Q.02] Given a numpy array 'arr', check if its data type is float 64 ?
''' arr = np.array([1.5,2.6,3.7])'''

arr = np.array([1.5,2.6,3.7])

is_float = np.dtype(arr.dtype) == np.dtype('float64')

print("is data type float64 :",is_float)

is data type float64 : True


In [3]:
# Q.03] Create a numpy array 'arr' with a datatype of complex128 containing the three complex numbers ?

arr = np.array([1+2j,3+4j,5+6j])
print(arr.dtype)

print(arr)

complex128
[1.+2.j 3.+4.j 5.+6.j]


In [4]:
# Q.04] Convert an existing numpy array 'arr' of integers to float 32 data type ?

arr = np.array([1,2,3,4,5])

arr_float32 = arr.astype(np.float32)

print(arr_float32)
print(arr_float32.dtype)

[1. 2. 3. 4. 5.]
float32


In [5]:
# Q.05] Given a numpy array 'arr' with float64 data type, convert it to float32 to reduce decimal precison ?

arr = np.array([1.5,2.6,3.7])

arr_float32 = arr.astype(np.float32)

print(arr_float32)
print(arr_float32.dtype)



[1.5 2.6 3.7]
float32


In [6]:
# Q.06] Write a function array_attributes that takes a numpy array as input and returns its shape, size and data type ?

def array_attributes(arr):
  shape = arr.shape
  size = arr.size
  dtype = arr.dtype
  return shape, size, dtype

arr = np.array([[1,2,3], [4,5,6]])
result = array_attributes(arr)
print(result)

((2, 3), 6, dtype('int64'))


In [7]:
# Q.07] Create a function array dimension that takes a numpy array as input and returns its dimensionality ?

def array_dimension(arr):
  dimension = arr.ndim
  return dimension

arr = np.array([[1,2,3], [4,5,6]])
result = array_dimension(arr)
print("ndim :",result)

ndim : 2


In [8]:
# Q.08] design a function item_size_info that takes a numpy array as input and returns the item size and the total size in byts ?

def item_size_info(arr):
  item_size = arr.itemsize
  total_size = arr.nbytes
  return item_size, total_size

arr = np.array([[1, 2, 3], [4, 5, 6]])  # 4 bytes per element
result = item_size_info(arr)
print(result)


(8, 48)


In [9]:
# Q.09] Create a function array_strides that takes a numpy as input and returns the strides of the array ?

def array_strides(arr):
   return arr.strides

arr = np.array([[1,2,3], [4,5,6]])
result = array_strides(arr)
print(result)

(24, 8)


In [10]:
# Q.10] Design a function shape_stride_relationship that takes a numpy array as input and returns the shape and strides of the array ?

def shape_stride_relationship(arr):

  shape = arr.shape
  strides = arr.strides
  return shape, strides

arr = np.array([[1,2,3], [4,5,6]])
result = shape_stride_relationship(arr)
print(result)



((2, 3), (24, 8))


In [11]:
# Q.11] Create a function create_zeros_array that takes an integer 'n' as input and returns a numpy array of zeros with 'n' elements ?

def create_zeros_array(n):
  zeros_array = np.zeros(n)
  return zeros_array

result = create_zeros_array(5)
print(result)

[0. 0. 0. 0. 0.]


In [12]:
# Q.12] write a function 'create_ones_matrix' that takes integers 'rows' and 'cols' as inputs and generates a 2D numpy array filled with ones of size 'rows * cols' ?

def create_ones_matrix(rows, cols):
  ones_matrix = np.ones((rows, cols))
  return ones_matrix

result = create_ones_matrix(3,4)
print(result)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:
# Q.13] Write a funnction 'generate_range_array' that takes three integers start, stop and step as arguments and creates a numpy array with a range starting from 'start' ending at stop (exculsive), and with the specified step ?

def generate_range_array(start, stop, step):

  return np.arange(start, stop, step)

result = generate_range_array(0,10,2)
print(result)


[0 2 4 6 8]


In [14]:
# Q.14] Design a function 'generate_linear_space' that takes two floats 'start', 'stop' and an integer 'num' as arguments and generates a numpy array with num equally spaced values between 'start' and 'stop' (inclusive) ?

def generate_linear_space(start, stop, num):

  return np.linspace(start, stop, num)

result = generate_linear_space(0,1,5)
print(result)

[0.   0.25 0.5  0.75 1.  ]


In [15]:
# Q.15] Create a function 'create_identity_matrix' that takes in integer 'n' as input and generates a square identity matrix of size 'n * n' using numpy.eye ?

def create_identity_matrix(n):

  return np.eye(n)

result = create_identity_matrix(3)
print(result)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
# Q.16] Write a function that takes a python list and converts it into a numpy array ?

l = [1,2,3,4,5]
np.array(l)


array([1, 2, 3, 4, 5])

In [17]:
# Q.17] Create a numpy array and demonstrate the use of numpy.view to create a new array object with the same data ?

arr = np.array([10,20,30,40])
view_arr = arr.view()

print("original array :", arr)
print("View array :", view_arr)

original array : [10 20 30 40]
View array : [10 20 30 40]


In [18]:
# Q.18] Write a function that takes two numpy arrays and concatenate them along a specified axis ?

def concatenate_arrays(arr1, arr2, axis):
  concatenated_arr = np.concatenate((arr1, arr2), axis = axis)
  return concatenated_arr

arr1 = np.array([[1,2,3], [4,5,6]])
arr2 = np.array([[7,8,9], [10,11,12]])
result = concatenate_arrays(arr1, arr2, axis = 0)
print(result)



[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [19]:
# Q.19] Create a two numpy arrays with different shapes and concatenate them horizontally using numpy concatenate ?

arr1 = np.array ([1,2,3])
arr2 = np.array([4,5,6])

arr3 = np.concatenate((arr1, arr2))
print(arr3)

[1 2 3 4 5 6]


In [20]:
# Q.20] Write a function that vertically stacks multiple numpy arrays given as a list ?

def vertical_stack(arr):

  return np.vstack(arr)

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr3 = np.array([7,8,9])
result = vertical_stack((arr1, arr2, arr3))
print(result)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
# Q.21] Write a python function using numpy to create an array of integers within a specified range(inclusive) with a given step size ?

def create_range_array(start, stop, step):
  return np.arange(start, stop, step)

arr = create_range_array(0,10,3)
print(arr)

[0 3 6 9]


In [22]:
# Q.22] Write a python function using numpy to generate an array of 10 equally spaced values between 0 and 1(inclusive) ?

def generate_array():
  return np.linspace(0,1,10)

result = generate_array()
print(result)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [23]:
# Q.22] Write a python function using numpy to generate an array of 10 equally spaced values between 0 and 1(inclusive) ?

def generate_array():
  return np.linspace(0,1,10)

result = generate_array()
print(result)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [24]:
# Q.24] Create a Pandas DataFrame using numpy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100 ?

import pandas as pd
import numpy as np

data = np.random.randint(1,100, (5,3))
df = pd.DataFrame(data, columns = ['a','b', 'c'])
print(df)

    a   b   c
0  37  90  20
1  38  62   7
2  23  84  29
3  22  45  88
4   7  38  61


In [25]:
# Q.25] Write a function that takes a pandas DataFrame and replaces all negative values in a specific column with zeros. use numpy operations within the Pandas DataFrame ?

def replace_negative_values(df, column_name):
  df[column_name] = df[column_name].apply(lambda x: 0 if x < 0 else x)

replace_negative_values(df, 'a')
print(df)

    a   b   c
0  37  90  20
1  38  62   7
2  23  84  29
3  22  45  88
4   7  38  61


In [26]:
# Q.26] Acess the 3rd element from the given numpy array ''' arr = np.array([10,20,30,40,50])''' ?

arr = np.array([10,20,30,40,50])
print(arr[2])




30


In [27]:
# Q.27] Retrieve the element at index (1,2) from the 2D numpy array ?
''' arr = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]])'''

arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

element = arr[1,2]
print(element)

6


In [28]:
# Q.28] Using boolean indexing, extract elements greater than 5 from the given numpy array?
''' arr = np.array([3,8,2,10,5,7])'''

arr = np.array([3,8,2,10,5,7])
result = arr[arr > 5]
print(result)

[ 8 10  7]


In [29]:
# Q.29] Perform basic slicing to extract element from index 2 to 5 inclusive from the given numpy array ?
''' arr = np.array([1,2,3,4,5,6,7,8,9])'''

arr = np.array([1,2,3,4,5,6,7,8,9])
result = arr[2:6]
print(result)

[3 4 5 6]


In [30]:
# Q.30] Slice the 2D numpy array to extract the sub-array[[2,3], [5,6]] from the given array ?
''' arr_2D = np.array([[1,2,3],
                       [4,5,6],
                       [7,8,9]])'''

arr_2D = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

sub_array = arr_2D[0:2, 1:3]
print(sub_array)


[[2 3]
 [5 6]]


In [31]:
# Q.32] Write a numpy function to extract elements in specific order from a given 2D array based on indices provided in another array ?

def extract_elements(arr,indices):
  return arr[indices]

arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
indices = np.array([0,2])
result = extract_elements(arr,indices)
print(result)

[[1 2 3]
 [7 8 9]]


In [32]:
# Q.33] Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension. ?

def extract_elements(arr, indices_x, indices_y, indices_z):
  return arr[indices_x, indices_y, indices_z]

arr = np.array([[[1,2,3],
                 [4,5,6],
                 [7,8,9],
                 [10,11,12]]])
indices_x = np.array([0,0])
indices_y = np.array([1,2])
indices_z = np.array([1,2])
result = extract_elements(arr, indices_x, indices_y, indices_z)
print(result)

[5 9]


In [33]:
# Q.34]  Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing. ?

def extract_elements(arr, condt1 , condt2):
  return arr[(arr > condt1) & (arr < condt2)]

arr = np.array([1,2,3,4,5,6,7,8,9])
result = extract_elements(arr, 3,7)
print(result)

[4 5 6]


In [34]:
# Q.35] Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays. ?

def extract_elements(arr, row_indices, col_indices):
  return arr[row_indices, col_indices]

arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
row_indices = np.array([0,1])
col_indices = np.array([1,2])
result = extract_elements(arr, row_indices, col_indices)
print(result)

[2 6]


In [35]:
# Q.36] Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting. ?

def add_scalar(arr, scalar):
  return arr + scalar

arr = np.array([[10,20,30],
                [40,50,60],
                [70,80,90]])
scalar = 5
result = add_scalar(arr, scalar)
print(result)

[[15 25 35]
 [45 55 65]
 [75 85 95]]


In [36]:
# Q.37] Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting. ?

def multiply_rows(arr1, arr2):
  return arr2 * arr1.T

arr1 = np.array([[2,3,4]])
arr2 = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12]])
result = arr2 * arr1.T
print(result)

[[ 2  4  6  8]
 [15 18 21 24]
 [36 40 44 48]]


In [37]:
# Q.38] Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting. ?

def add_two_arrays(arr1, arr2, axis = 0):
  return (arr2.T + arr1).T

arr1 = np.array([[1,2,3,4]])
arr2 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9],
                 [10,11,12]])
result = add_two_arrays(arr1, arr2, axis = 0)
print(result)

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]


In [38]:
# Q.39] Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.

def add_arrays(arr1, arr2):
  return arr2 + arr1

arr1 = np.array([[1],
                 [2],
                 [3]])
arr2 = np.array([[10,20,30]])
result = add_arrays(arr1, arr2)
print(result)


[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [39]:
# Q.40] Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility. ?

def multiply_arrays(arr1, arr2):
   arr1_reshaped = arr1.reshape(2, 1, 3)

   arr2_reshaped = arr2.reshape(2, 2, 1)

   return arr1_reshaped * arr2_reshaped

arr1 = np.array([[1,2,3],
                 [4,5,6]])
arr2 = np.array([[10,20],
                 [30,40]])
result = multiply_arrays(arr1, arr2)
print(result)

[[[ 10  20  30]
  [ 20  40  60]]

 [[120 150 180]
  [160 200 240]]]


In [40]:
# Q.41] Calculate column-wise mean for the given array: arr = np.array([[1, 2, 3], [4, 5, 6]]) ?

arr = np.array([[1, 2, 3], [4, 5, 6]])
result = np.mean(arr)
print(result)

3.5


In [41]:
# Q.42] Find maximum value in each row of the given array: arr = np.array([[1, 2, 3], [4, 5, 6]]) ?

arr = np.array([[1, 2, 3], [4, 5, 6]])
result = np.max(arr, axis = 1)
print(result)

[3 6]


In [42]:
# Q.43] For the given array, find indices of maximum value in each column. arr = np.array([[1, 2, 3], [4, 5, 6]]) ?

arr = np.array([[1, 2, 3], [4, 5, 6]])
result = np.argmax(arr)
print(result)

5


In [43]:
# Q.44] For the given array, apply custom function to calculate moving sum along rows. arr = np.array([[1, 2, 3], [4, 5, 6]]) ?

arr = np.array([[1, 2, 3], [4, 5, 6]])
result = np.cumsum(arr, axis = 1)
print(result)

[[ 1  3  6]
 [ 4  9 15]]


In [44]:
# Q.45] In the given array, check if all elements in each column are even. arr = np.array([[2, 4, 6], [3, 5, 7]]) ?

arr = np.array([[2, 4, 6], [3, 5, 7]])
result = (arr % 2 == 0)
print(result)

[[ True  True  True]
 [False False False]]


In [45]:
# Q.46] Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix. original_array = np.array([1, 2, 3, 4, 5, 6]) ?

def reshape_array(arr, m, n):
    return arr.reshape(m, n)

original_array = np.array([1, 2, 3, 4, 5, 6])
reshaped = reshape_array(original_array, 2, 3)
print(reshaped)

[[1 2 3]
 [4 5 6]]


In [46]:
# Q.47] Create a function that takes a matrix as input and returns the flattened array. input_matrix = np.array([[1, 2, 3], [4, 5, 6]]) ?

def flatten_matrix(input_matrix):
  return input_matrix.flatten()

input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
result = flatten_matrix(input_matrix)
print(result)

[1 2 3 4 5 6]


In [47]:
# Q.48] Write a function that concatenates two given arrays along a specified axis. array1 = np.array([[1, 2], [3, 4]]) array2 = np.array([[5, 6], [7, 8]]) ?

def concatenate_arrays(array1, array2, axis):
  return np.concatenate((array1, array2), axis = axis)

array1 = np.array([[1,2], [3,4]])
array2 = np.array([[5,6], [7,8]])
result = concatenate_arrays(array1, array2, axis = 0)
print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [48]:
# Q.49] Create a function that splits an array into multiple sub-arrays along a specified axis. original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) ?

def split_array(original_array, indices_or_sections, axis = 0):
  return np.split(original_array, indices_or_sections, axis = axis)

original_array = np.array([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]])

result = split_array(original_array, 3, axis=0)
for sub_array in result:
  print(result)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [49]:
# Q.50] Write a function that inserts and then deletes elements from a given array at specified indices. original_array = np.array([1, 2, 3, 4, 5]), indices_to_insert = [2, 4], values_to_insert = [10, 11], indices_to_delete = [1, 3] ?

def insert_and_delete(original_array, indices_to_insert, values_to_insert, indices_to_delete):
  new_array = np.insert(original_array, indices_to_insert, values_to_insert)
  final_array = np.delete(new_array, indices_to_delete)
  return final_array

original_array = np.array([1,2,3,4,5])
indices_to_insert = [2,4]
values_to_insert = [10,11]
indices_to_delete = [1,3]
result = insert_and_delete(original_array, indices_to_insert, values_to_insert, indices_to_delete)
print(result)

[ 1 10  4 11  5]


In [50]:
# Q.51] Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. Perform element-wise addition between `arr1` and `arr2`. ?

arr1 = np.random.randint(1,100, (3,3))
arr2 = np.arange(1, 10).reshape(3, 3)
result = arr1 + arr2
print(result)


[[ 82  95  21]
 [102  52  86]
 [ 43  11  87]]


In [51]:
# Q.52] Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers from 1 to 10. Subtract `arr2` from `arr1` element-wise. ?

arr1 = np.arange(10,0,-1)
arr2 = np.arange(1,11)
result = arr1 - arr2
print(result)

[ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [52]:
# Q.53] Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5. Perform element-wise multiplication between `arr1` and `arr2`. ?

arr1 = np.random.randint(1,10, size = 5)
arr2 = np.array([1,2,3,4,5])

result = arr1 * arr2
print(result)

[ 4 10 12 20 45]


In [53]:
# Q.54] Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 to 5. Perform element-wise division of `arr1` by `arr2`. ?

arr1 = np.array([2,4,6,8,10])
arr2 = np.array([1,2,3,4,5])

result = arr1 / arr2
print(result)

[2. 2. 2. 2. 2.]


In [54]:
# Q.55] Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise. ?

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([5,4,3,2,1])

result = arr1 ** arr2
print(result)

[ 1 16 27 16  5]


In [55]:
# Q.56] Write a function that counts the occurrences of a specific substring within a NumPy array of strings.arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello']) ?

def count_substring(arr, substring):
    return np.char.count(arr, substring).sum()

arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
substring = 'hello'

count = count_substring(arr, substring)
print(f"'{substring}' occurs {count} times.")



'hello' occurs 3 times.


In [56]:
# Q.57] Write a function that extracts uppercase characters from a NumPy array of strings. arr = np.array(['Hello', 'World', 'OpenAI', 'GPT']) ?


def extract_uppercase(arr):
    return np.array([char for word in arr for char in word if char.isupper()])

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
print(extract_uppercase(arr))

['H' 'W' 'O' 'A' 'I' 'G' 'P' 'T']


In [57]:
# Q.58] Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string. arr = np.array(['apple', 'banana', 'grape', 'pineapple']) ?

def replace_substring(arr, old_sub, new_sub):
  return np.char.replace(arr, old_sub, new_sub)

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
result = replace_substring(arr, 'apple', 'orange')
print(result)

['orange' 'banana' 'grape' 'pineorange']


In [58]:
# Q.59]  Write a function that concatenates strings in a NumPy array element-wise.arr1 = np.array(['Hello', 'World']), arr2 = np.array(['Open', 'AI']) ?

def concatenate_strings(arr1, arr2):
  return arr1 + arr2

arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])
result = concatenate_strings(arr1, arr2)
print(result)

['HelloOpen' 'WorldAI']


In [59]:
# Q.60] Write a function that finds the length of the longest string in a NumPy array. arr = np.array(['apple', 'banana', 'grape', 'pineapple']) ?

def find_longest_string(arr):
  return max(arr, key = len)

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
result = find_longest_string(arr)
print(result)

pineapple


In [62]:
# Q.61] Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using NumPy's functions ?

data = np.random.randint(1,1001, size = 1000)

mean = np.mean(data)
median = np.median(data)
variance = np.var(data)
std_deviation = np.std(data)

print(mean)
print(median)
print(variance)
print(std_deviation)

489.192
477.5
80332.899136
283.4305896264551


In [65]:
# Q.62] Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset. ?

data = np.random.randint(1,101, 50)
percentile_25 = np.percentile(data, 25)
percentile_75 = np.percentile(data, 75)

print(percentile_25)
print(percentile_75)

30.5
71.0


In [66]:
# Q.63] Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's `corrcoef` function. ?

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

correlation_coefficient = np.corrcoef(arr1, arr2)
print(correlation_coefficient)

[[1. 1.]
 [1. 1.]]


In [67]:
# Q.64] Create two matrices and perform matrix multiplication using NumPy's `dot` function. ?

matrix1 = np.array([[1,2], [3,4]])
matrix2 = np.array([[5,6],[7,8]])

result = np.dot(matrix1, matrix2)
print(result)

[[19 22]
 [43 50]]


In [70]:
# Q.65] Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles. ?

data = np.random.randint(10, 1001, size=50)

percentile_10 = np.percentile(data, 10)
median = np.median(data)
percentile_90 = np.percentile(data, 90)

quartile_1 = np.percentile(data, 25)
quartile_3 = np.percentile(data, 75)

print(percentile_10)
print(median)
print(percentile_90)
print(quartile_1)
print(quartile_3)


95.50000000000001
482.0
892.5
265.5
798.5


In [72]:
# Q.66]  Create a NumPy array of integers and find the index of a specific element. ?


arr = np.array([10, 20, 30, 40, 50])
index = list(arr).index(30)

print(index)

2


In [78]:
# Q.67] Generate a random NumPy array and sort it in ascending order. ?

arr = np.random.randint(0,10, size = 10)
sorted_asc = np.sort(arr)

print(arr)
print(sorted_desc)

[8 5 4 1 3 2 1 8 5 2]
[1 1 2 4 5 6 6 7 8 9]


In [80]:
# Q.68] Filter elements >20  in the given NumPy array. arr = np.array([12, 25, 6, 42, 8, 30]) ?

arr = np.array([12,25,6,42,8,30])
filter = arr > 20
result = arr[filter]
print(result)

[25 42 30]


In [81]:
# Q.69] Filter elements which are divisible by 3 from a given NumPy array. arr = np.array([1, 5, 8, 12, 15]) ?

arr = np.array([1,5,8,12,15])
filter = arr % 3 == 0
result = arr[filter]
print(filter)

[False False False  True  True]


In [83]:
# Q.70] Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array. arr = np.array([10, 20, 30, 40, 50]) ?

arr = np.array([10,20,30,40,50])
filter = (arr >= 20) & (arr <=40)
result = arr[filter]
print(result)

[20 30 40]


In [84]:
# Q.71]  For the given NumPy array, check its byte order using the `dtype` attribute byteorder. arr = np.array([1, 2, 3])


arr = np.array([1, 2, 3])
print(arr.dtype.byteorder)

=


In [86]:
# Q.72] For the given NumPy array, perform byte swapping in place using `byteswap()`. arr = np.array([1, 2, 3], dtype=np.int32) ?

arr = np.array([1, 2, 3], dtype=np.int32)
arr.byteswap(inplace = True)
print(arr)

[16777216 33554432 50331648]


In [92]:
# Q.73] For the given NumPy array, swap its byte order without modifying the original array using `newbyteorder()`. arr = np.array([1, 2, 3], dtype=np.int32) ?

arr = np.array([1, 2, 3], dtype=np.int32)
swapped = arr.view(arr.dtype.newbyteorder())
print(arr)
print(swapped)

[1 2 3]
[16777216 33554432 50331648]


In [93]:
# Q.74] For the given NumPy array and swap its byte order conditionally based on system endianness using `newbyteorder()`. arr = np.array([1, 2, 3], dtype=np.int32) ?

import sys
arr = np.array([1,2,3], dtype = np.int32)
if sys.byteorder == 'little':
  swapped = arr.view(arr.dtype.newbyteorder('big'))
else:
  swapped = arr.view(arr.dtype.newbyteorder('little'))
print(arr)
print(swapped)

[1 2 3]
[16777216 33554432 50331648]


In [94]:
# Q.75] For the given NumPy array, check if byte swapping is necessary for the current system using `dtype`attribute `byteorder`. arr = np.array([1, 2, 3], dtype=np.int32) ?

arr = np.array([1,2,3], dtype = np.int32)
print(arr.dtype.byteorder)


=


In [102]:
# Q.76]  Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`. ?

import sys

arr = np.array([1, 2, 3], dtype=np.int32)

# Check the byte order of the array and system
arr_byteorder = arr.dtype.byteorder
system_byteorder = '<' if sys.byteorder == 'little' else '>'

# Determine if swapping is necessary
if arr_byteorder != '=' and arr_byteorder != system_byteorder:
    print("Byte swapping is necessary.")
else:
    print("Byte swapping is NOT necessary.")

print("Array byte order:", arr_byteorder)
print("System byte order:", system_byteorder)

Byte swapping is NOT necessary.
Array byte order: =
System byte order: <


In [103]:
# Q.77] Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`. ?

matrix = np.random.randint(0,10, size = (3,3))
print(matrix)

view_slice = matrix[1:3, 1:3]
print(view_slice)

view_slice[0,0] = 99
print(view_slice)
print(matrix)

[[8 6 4]
 [2 6 1]
 [1 9 2]]
[[6 1]
 [9 2]]
[[99  1]
 [ 9  2]]
[[ 8  6  4]
 [ 2 99  1]
 [ 1  9  2]]


In [105]:
# Q.78]  Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`. ?

array_a = np.arange(1,13).reshape(4,3)
view_b = array_a[1:3, 1:3]
view_b +=5
print(array_a)
print(view_b)

[[ 1  2  3]
 [ 4 10 11]
 [ 7 13 14]
 [10 11 12]]
[[10 11]
 [13 14]]


In [107]:
# Q.79] Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view `reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it reflects changes in the original `orig_array`. ?

orig_array = np.arange(1,9).reshape(2,4)
reshaped_view = orig_array.reshape(4,2)
reshaped_view[0,0] = 99
print(orig_array)
print(reshaped_view)

[[99  2  3  4]
 [ 5  6  7  8]]
[[99  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]]


In [109]:
# Q.80] Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`. ?

data = np.random.randint(0,10, size = (3,4))
data_copy = data[data > 5].copy()
data_copy[0] = 99
print(data)
print(data_copy)

[[3 4 9 5]
 [2 3 0 9]
 [1 7 6 0]]
[99  9  7  6]


In [110]:
# Q.81] Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them. ?

A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

addition = A + B
substraction = A - B

print(addition)
print(substraction)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]


In [111]:
# Q.82] Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication. ?

C = np.array([[1,2], [3,4], [5,6]])
D = np.array([[7,8,9,10], [11,12,13,14]])

result = np.dot(C,D)
print(result)

[[ 29  32  35  38]
 [ 65  72  79  86]
 [101 112 123 134]]


In [112]:
# Q.83] Create a matrix `E` and find its transpose. ?

E = np.array([[1,2,3], [4,5,6]])
result = E.T
print(result)

[[1 4]
 [2 5]
 [3 6]]


In [113]:
# Q.84] Generate a square matrix `F` and compute its determinant. ?

F = np.array([[1,2], [3,4]])
result = np.linalg.det(F)
print(result)

-2.0000000000000004


In [114]:
# Q.85] Create a square matrix `G` and find its inverse ?

G = np.array([[1,2], [3,4]])
result = np.linalg.inv(G)
print(result)


[[-2.   1. ]
 [ 1.5 -0.5]]
